// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: newsfeed_service.proto
#ifndef GRPC_newsfeed_5fservice_2eproto__INCLUDED
#define GRPC_newsfeed_5fservice_2eproto__INCLUDED

#include "newsfeed_messages.pb.h"

#include <grpc++/impl/codegen/async_stream.h>
#include <grpc++/impl/codegen/async_unary_call.h>
#include <grpc++/impl/codegen/method_handler_impl.h>
#include <grpc++/impl/codegen/proto_utils.h>
#include <grpc++/impl/codegen/rpc_method.h>
#include <grpc++/impl/codegen/service_type.h>
#include <grpc++/impl/codegen/status.h>
#include <grpc++/impl/codegen/stub_options.h>
#include <grpc++/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class RpcService;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace newsfeed {
namespace proto {

class Newsfeed final {
 public:
  static constexpr char const* service_full_name() {
    return "newsfeed.proto.Newsfeed";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>> Talk(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>>(TalkRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>> AsyncTalk(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>>(AsyncTalkRaw(context, cq, tag));
    }
  private:
    virtual ::grpc::ClientReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* TalkRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* AsyncTalkRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>> Talk(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>>(TalkRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>> AsyncTalk(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>>(AsyncTalkRaw(context, cq, tag));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* TalkRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* AsyncTalkRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    const ::grpc::RpcMethod rpcmethod_Talk_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Talk(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Talk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Talk() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Talk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Talk(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestTalk(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Talk<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Talk : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Talk() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Talk() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Talk(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::newsfeed::proto::req_envelope, ::newsfeed::proto::req_envelope>* stream) final override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace proto
}  // namespace newsfeed


#endif  // GRPC_newsfeed_5fservice_2eproto__INCLUDED
